tomzo/gocd-yaml-config-plugin

- build.gradle
- src/main/java/cd/go/plugin/config/yaml/YamlFileParser.java
- src/test/java/cd/go/plugin/config/yaml/TestUtils.java
- src/test/java/cd/go/plugin/config/yaml/YamlConfigPluginIntegrationTest.java
- src/test/java/cd/go/plugin/config/yaml/transforms/RootTransformTest.java
- src/test/resources/examples/duplicate-materials.gocd.yaml
- src/test/resources/parts/roots/duplicate.materials.pipe.yaml
@tomzo I had to change the yamlbeans dependency repo location as I could not get authorization to the original maven repo to release a new jar there. I created my own repository com.github.sanjusoftware.yamlbeans and release the new 1.11 version of yaml beans there. used the same as dependency here in this release instead. Hope there is no concerns for this change.
this should fix issue #3
> fix for issue #3

- src/main/java/cd/go/plugin/config/yaml/YamlFileParser.java
- src/test/java/cd/go/plugin/config/yaml/YamlConfigPluginIntegrationTest.java
- src/test/resources/examples/invalid-materials.gocd.yaml
this happened very recently to me, when I by accident ended up entering a tilde (~) sign in the YAML file. When I pushed the changes, then it started throwing the error `IO error when reading Go YAML file` because thats the last exception that gets caught. However, this just ate the actual message which was `Error parsing YAML. : Line 21, column 0: .....`
This made me spend time debugging in wrong direction, where in I was suspecting maybe something went wrong with the repo url, or repo permissions etc. 
After a long time, I could figure out that there was an accidental '~' in the file which was causing the problem. I think its better to surface the actual error for the Devs (mostly devs are using these plugins etc)
> file parser errors being thrown as IO errors, which is misleading

- README.md
- src/main/java/cd/go/plugin/config/yaml/AntDirectoryScanner.java
- src/main/java/cd/go/plugin/config/yaml/JsonConfigCollection.java
- src/main/java/cd/go/plugin/config/yaml/YamlConfigPlugin.java
- src/main/java/cd/go/plugin/config/yaml/YamlFileParser.java
- src/main/java/cd/go/plugin/config/yaml/transforms/PipelineTransform.java
- src/main/java/cd/go/plugin/config/yaml/transforms/RootTransform.java
- src/main/resources/plugin-settings.template.html
- src/test/java/cd/go/plugin/config/yaml/AntDirectoryScannerTest.java
- src/test/java/cd/go/plugin/config/yaml/YamlConfigPluginIntegrationTest.java
- src/test/java/cd/go/plugin/config/yaml/transforms/PipelineTransformTest.java
- src/test/java/cd/go/plugin/config/yaml/transforms/RootTransformTest.java
- src/test/resources/examples.out/README.md
- src/test/resources/parts/lock_behavior.pipe.json
- src/test/resources/parts/lock_behavior.pipe.yaml
- src/test/resources/parts/roots/version_1.yaml
- src/test/resources/parts/roots/version_2.yaml
- src/test/resources/parts/roots/version_not_present.yaml
Equivalent of https://github.com/tomzo/gocd-json-config-plugin/pull/12 for the yaml plugin.
Does this:
1. Updates README: Mostly Go => GoCD and *.go.cd to *.gocd.org.
2. Accept multiple patterns in the settings file. Old (single) patterns work too.
3. Allow specifying target version in the YAML.
4. Accept `lock_behavior` in the YAML.
It'll be like this, for every file:
```
format_version: 2
environments:
env1: ...
env2: ...
pipelines:
pipe1:
lock_behavior: "lockOnFailure"
...
```
> Allow specifying target version

- .gitignore
- build.gradle
- src/main/java/cd/go/plugin/config/yaml/transforms/EnvironmentsTransform.java
- src/main/java/cd/go/plugin/config/yaml/transforms/RootTransform.java
- src/main/java/cd/go/plugin/config/yaml/transforms/TaskTransform.java
- src/test/java/cd/go/plugin/config/yaml/transforms/RootTransformTest.java
- src/test/resources/parts/roots/pipeline_order.yaml
Fixes #4.
I couldn't find a reason why the sanjusoftware fork of yamlbeans was being used - perhaps the original issue has since been fixed in the main yamlbeans releases?
I did have to change a small number of conditionals in existing transforms, as a key without a value is read as `null` instead of an empty string by this yamlbeans version. Otherwise, the ordering comes for free and I've added a test to verify it.
> Preserve order of pipelines within a group

- README.md
The `group` attribute must be specified for a pipeline. Bit of a pain to copy paste this only to get an error thrown.
> Use valid pipeline example in README

- README.md
This helps to avoid confusion which name: pipeline name or material name should be used in fetch task.
> Update README: unify which pipeline name to use in fetch task

- src/main/java/cd/go/plugin/config/yaml/cli/YamlPluginCli.java
No need to prepend "." to files
- redundant for rel paths
- breaks abs paths (and ad-hoc file descriptor args, e.g. /dev/fd/XX)
> Fix absolute paths and file descriptor refs in CLI

- build.gradle
- src/main/java/cd/go/plugin/config/yaml/Capabilities.java
- src/main/java/cd/go/plugin/config/yaml/ConfigRepoMessages.java
- src/main/java/cd/go/plugin/config/yaml/JsonConfigCollection.java
- src/main/java/cd/go/plugin/config/yaml/YamlConfigPlugin.java
- src/test/java/cd/go/plugin/config/yaml/YamlConfigPluginIntegrationTest.java
As part of the GoCD CLI we want to support a preflight function to validate potential changes to a config. The preflight function will be a public API so we want to be able to parse arbitrary strings vs reading contents from a file system. This is what parse content does. 
Corresponding PR https://github.com/gocd/gocd/pull/5579 
Additional context https://github.com/gocd/gocd/issues/5489
> Add support for parsing the content of a file

- src/main/java/cd/go/plugin/config/yaml/ConfigRepoMessages.java
- src/main/java/cd/go/plugin/config/yaml/PluginSettings.java
- src/main/java/cd/go/plugin/config/yaml/YamlConfigPlugin.java
- src/test/java/cd/go/plugin/config/yaml/YamlConfigPluginIntegrationTest.java
Since the initial pipeline export work, we have been sending the wrong api version when
fetching plugin settings. This was causing some issues during parse directory. The general
move to extension v2 also caused some issues during plugin load. This PR resolves this.
@tomzo this needs to be merged, or else we'll be shipping broken plugins :/
> Fix plugin settings request and implement handler for plugin config change notification

- build.gradle
- src/main/java/cd/go/plugin/config/yaml/YamlConfigPlugin.java
Adds response headers to the API to give hints about the response payload (i.e., exported content):
- `Content-Type`: self-explanatory
- `X-Export-Filename`: non-standard header to suggest a filename for the content. This will be used to construct `Content-Disposition` in GoCD's new pipeline export links.
- _Why not use `Content-Disposition` directly?_ Firstly, this is a matter of opinion, and I'm open to alternatives. So here's the explanation: In GoCD, we really only want to know how to name the file we construct for pipeline export, so I didn't want to open the door for supporting other aspects of `Content-Disposition` from the plugin side (i.e., `attachment` vs `inline` vs `form-data` -- we just want the `; filename=XXX` segment). On the GoCD side, we will use this header to enforce a …
> Add export content metadata

- README.md
- src/main/java/cd/go/plugin/config/yaml/cli/YamlPluginCli.java
@tomzo One last (tiny) PR before cutting a stable release.
This is for the CLI output from the plugin jar; wanted to be consistent and always output JSON. The GoCD CLI should handle the presentation to the user.
> We should always return CLI results as JSON

- CHANGELOG.md
- src/main/java/cd/go/plugin/config/yaml/Capabilities.java
The returned JSON uses snake-cased keys, instead of the camel case keys
used earlier.
> Changed JSON keys returned by `get-capabilities` call

- .gitignore
- build.gradle
- buildSrc/build.gradle
- buildSrc/src/main/groovy/cd/go/plugin/buildsrc/license/NoticeFileGenerator.groovy
- buildSrc/src/main/groovy/cd/go/plugin/buildsrc/license/TeeRenderer.groovy
Should help avoid pulling in any dependencies that are incompatible
with the Apache 2.0 license.
Currently this works on the basis of a whitelist of approved licenses.
See `TeeRenderer.groovy` file for the approved list.
> Add a license checker for dependencies

- src/main/java/cd/go/plugin/config/yaml/transforms/ConfigurationTransform.java
- src/main/java/cd/go/plugin/config/yaml/transforms/JobTransform.java
- src/test/java/cd/go/plugin/config/yaml/transforms/JobTransformTest.java
- src/test/resources/parts/jobs/external_artifacts.json
- src/test/resources/parts/jobs/external_artifacts.yaml
Fixes https://github.com/gocd/gocd/issues/6038
The conversion is a little weird. This needs to get converted:
```json
{
"type": "external",
"id": "docker-release-candidate",
"store_id": "dockerhub",
"configuration": [
{
"key": "Image",
"value": "gocd/gocd-demo"
},
{
"key": "Tag",
"value": "Tag1"
},
{
"key": "some_secure_property",
"encrypted_value": "!@ESsdD323#sdu"
}
]
}
```
... to ...
```yaml
external:
id: docker-release-candidate
store_id: dockerhub
configuration:
options:
Image: gocd/gocd-demo
Tag: Tag1
secure_options:
some_secure_property: !@ESsdD323#sdu
```
So: From a `List<Map<String, String>>` to `Map<String, Map<String, String>>` with `options` and `secure_options` being the keys.
> Fix pipeline export of external artifacts

- CHANGELOG.md
- README.md
- build.gradle
- src/main/java/cd/go/plugin/config/yaml/transforms/PipelineTransform.java
- src/test/java/cd/go/plugin/config/yaml/transforms/PipelineTransformTest.java
- src/test/resources/parts/display_order.pipe.json
- src/test/resources/parts/display_order.pipe.yaml
* Introduce display_order_weight.
* Update README to reflect that a UI is now available to configure config repositories.
* Clarify usage of format_version.
* Code changes and tests.
@tomzo Haven't bumped the version, since this is at 0.9.0 already. Do you want: `0.10.0`? `1.0.0`? Wasn't sure.
Related to https://github.com/gocd/gocd/pull/6043
> Add ability to control display order of pipelines on the GoCD dashboard

- .travis.yml
- CHANGELOG.md
- Dojofile
- Idefile
- LICENSE
- README.md
- ci.gocd.yaml
- tasks.sh
All builds (public on travis and GoCD) will execute in same [docker image](https://github.com/kudulab/docker-openjdk-dojo) using [Dojo](https://github.com/ai-traders/dojo) from now on.
> switch build system to use open source openjdk-dojo image

- README.md
- src/test/java/cd/go/plugin/config/yaml/transforms/MaterialTransformTest.java
- src/test/resources/parts/materials/branch.hg.json
- src/test/resources/parts/materials/branch.hg.yaml
- src/test/resources/parts/materials/complete.git.json
- src/test/resources/parts/materials/complete.git.yaml
- src/test/resources/parts/materials/complete.hg.json
- src/test/resources/parts/materials/complete.hg.yaml
- src/test/resources/parts/materials/password.git.json
- src/test/resources/parts/materials/password.git.yaml
- src/test/resources/parts/materials/password.hg.json
- src/test/resources/parts/materials/password.hg.yaml
**This should not be merged until 19.4.0 is merged as the contract won't be released until then.**
- Document `format_version 5` - support for `username` and `encrypted_password / password` field while specifying git and hg material.
- Updated test cases
GoCD issue for reference: [#6132](https://github.com/gocd/gocd/issues/6132)
> support for username and encrypted_password / password field for git and hg material

- src/main/java/cd/go/plugin/config/yaml/transforms/MaterialTransform.java
- src/test/java/cd/go/plugin/config/yaml/transforms/MaterialTransformTest.java
- src/test/resources/parts/materials/complete.p4.yaml
- src/test/resources/parts/materials/complete.scm.json
- src/test/resources/parts/materials/complete.scm.yaml
The test was comparing a json file to itself. Fixed it to read the yaml file, inverse-transform it, and compare it with the json file.
This caught a few issues in the json and yaml files -
- complete.p4.yaml - needed block chomping for the multiline string
- complete.scm.yaml - scmId is required, which was missing. Had to change the order of some fields, because we are comparing LinkedHashMaps in the test. As such, the order shouldn't matter in the yaml unless its a sequence.
> Fix the inverse transform test for MaterialTransform

- README.md
Fixes typos spotted in the README - `verison` instead of `version`
> Fix typos - verison to version

- CHANGELOG.md
- src/main/java/cd/go/plugin/config/yaml/transforms/MaterialTransform.java
- src/test/java/cd/go/plugin/config/yaml/transforms/MaterialTransformTest.java
- src/test/java/cd/go/plugin/config/yaml/transforms/PipelineTransformTest.java
* Exporting a pipeline with multiple materials without a name would
result in yaml without all the materials, this commit fixes this
issue.
> Fix for export of pipelines with multiple materials without name #144

- README.md
- Updated the example to showcase configuring a secure configuration property.
I was testing some feature related to plugin materials and had to configure a secure field. Initially I thought of passing the encrypted_value in the options itself. But that was treated as value.
Found the `secure_options` field after going through the code and seeing the example of configuring pluggable tasks.
Raising this PR so that it is easier for other users.
> Update reference example for plugin material

- CHANGELOG.md
- Dojofile
- build.gradle
This PR also includes patch version bump, but I can revert it if needed.
> use newer openjdk Dojo image kudulab/openjdk-dojo:1.4.1

- README.md
It's not immediately clear that you can have multiple patterns by comma-separating them. So, this is a minor update for the README to indicate that.
What do you think? 🙂
> Update file pattern documentation in README

- .github/dependabot.yml
- build.gradle
SnakeYaml < 1.31 has a few vulnerabilities reported against it which have been mitigated in `1.31`. Since config repos are "semi trusted" this is probably sensible for us to mitigate in the plugin.
This change
- resolves/removes noise from CVE-2022-25857 / CVE-2022-38749 / CVE-2022-38750 / CVE-2022-38751 / CVE-2022-38752
- enables dependabot to make these easier to deal with in future? 😀
> Upgrade snakeyaml (and other dependencies) to latest secure version
